import { defineConfig } from 'tsup';
import { existsSync } from 'fs';

// Build entry points - schemas are generated by build:schemas script
const entry: Record<string, string> = {
    index: 'src/index.ts',
};

// Add schemas if they exist (generated by build:schemas)
if (existsSync('src/schemas/index.ts')) {
    entry['schemas/index'] = 'src/schemas/index.ts';
}

export default defineConfig({
    entry,
    format: ['esm', 'cjs'],
    dts: true,
    clean: true,
    splitting: false,
    sourcemap: true,
    external: ['zod', /^@omnify-base\/.*/],
});
