import { defineConfig } from 'tsup';
import { existsSync } from 'fs';

// Build entry points - schemas are generated by build:schemas script
const entry: Record<string, string> = {
    index: 'src/index.ts',
    'testing/index': 'src/testing/index.ts',
};

// Add schemas if they exist (generated by build:schemas)
if (existsSync('src/schemas/index.ts')) {
    entry['schemas/index'] = 'src/schemas/index.ts';
}

export default defineConfig({
    entry,
    format: ['esm', 'cjs'],
    dts: true,
    clean: true,
    splitting: false,
    sourcemap: true,
    // External packages (not bundled)
    external: ['zod', 'react', 'react-dom', 'antd', '@ant-design/icons', '@tanstack/react-query'],
    // Force bundle @omnify-base (generated by omnify, not published to npm)
    noExternal: [/@omnify-base\/.*/],
    // Use esbuild alias to resolve @omnify-base from node_modules
    esbuildOptions(options) {
        options.alias = {
            '@omnify-base': './node_modules/@omnify-base',
        };
    },
});
