/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * Auto-generated TypeScript types from Omnify schemas.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: npx omnify generate
 */

import { z } from 'zod';
import type { DateTimeString } from './common';

/**
 * 支店キャッシュ
 */
export interface BranchCache {
  /** Primary key */
  id: string;
  /** Console Branch ID */
  console_branch_id: unknown;
  /** Console Organization ID */
  console_org_id: unknown;
  /** 支店コード */
  code: string;
  /** 支店名 */
  name: string;
  /** 本社 */
  is_headquarters: boolean;
  /** 有効 */
  is_active: boolean;
  /** Creation timestamp */
  created_at?: DateTimeString;
  /** Last update timestamp */
  updated_at?: DateTimeString;
  /** Soft delete timestamp */
  deleted_at?: DateTimeString;
}

// ============================================================================
// I18n (Internationalization)
// ============================================================================

/**
 * Unified i18n object for BranchCache
 * Contains model label and all field labels/placeholders
 */
export const branchCacheI18n = {
  /** Model display name */
  label: {"ja":"支店キャッシュ","en":"Branch Cache"},
  /** Field labels and placeholders */
  fields: {
    console_branch_id: {
      label: {"ja":"Console Branch ID","en":"Console Branch ID"},
    },
    console_org_id: {
      label: {"ja":"Console Organization ID","en":"Console Organization ID"},
    },
    code: {
      label: {"ja":"支店コード","en":"Branch Code"},
    },
    name: {
      label: {"ja":"支店名","en":"Branch Name"},
    },
    is_headquarters: {
      label: {"ja":"本社","en":"Is Headquarters"},
    },
    is_active: {
      label: {"ja":"有効","en":"Active"},
    },
  },
} as const;

// ============================================================================
// Zod Schemas
// ============================================================================

/** Field schemas for BranchCache */
export const baseBranchCacheSchemas = {
  console_branch_id: z.string(),
  console_org_id: z.string(),
  code: z.string().min(1).max(20),
  name: z.string().min(1).max(100),
  is_headquarters: z.boolean(),
  is_active: z.boolean(),
} as const;

/** Create schema for BranchCache (POST requests) */
export const baseBranchCacheCreateSchema = z.object({
  console_branch_id: baseBranchCacheSchemas.console_branch_id,
  console_org_id: baseBranchCacheSchemas.console_org_id,
  code: baseBranchCacheSchemas.code,
  name: baseBranchCacheSchemas.name,
  is_headquarters: baseBranchCacheSchemas.is_headquarters,
  is_active: baseBranchCacheSchemas.is_active,
});

/** Update schema for BranchCache (PUT/PATCH requests) */
export const baseBranchCacheUpdateSchema = baseBranchCacheCreateSchema.partial();

// ============================================================================
// Inferred Types
// ============================================================================

export type BaseBranchCacheCreate = z.infer<typeof baseBranchCacheCreateSchema>;
export type BaseBranchCacheUpdate = z.infer<typeof baseBranchCacheUpdateSchema>;

// ============================================================================
// I18n Helper Functions
// ============================================================================

/** Get model label for a specific locale */
export function getBranchCacheLabel(locale: string): string {
  return branchCacheI18n.label[locale as keyof typeof branchCacheI18n.label] ?? branchCacheI18n.label['en'] ?? 'BranchCache';
}

/** Get field label for a specific locale */
export function getBranchCacheFieldLabel(field: string, locale: string): string {
  const fieldI18n = branchCacheI18n.fields[field as keyof typeof branchCacheI18n.fields];
  if (!fieldI18n) return field;
  return fieldI18n.label[locale as keyof typeof fieldI18n.label] ?? fieldI18n.label['en'] ?? field;
}

/** Get field placeholder for a specific locale */
export function getBranchCacheFieldPlaceholder(field: string, locale: string): string {
  const fieldI18n = branchCacheI18n.fields[field as keyof typeof branchCacheI18n.fields];
  if (!fieldI18n || !('placeholder' in fieldI18n)) return '';
  const placeholder = fieldI18n.placeholder as Record<string, string>;
  return placeholder[locale] ?? placeholder['en'] ?? '';
}
