/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * Auto-generated TypeScript types from Omnify schemas.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: npx omnify generate
 */

import { z } from 'zod';
import type { DateTimeString } from './common';

/**
 * 組織キャッシュ
 */
export interface OrganizationCache {
  /** Primary key */
  id: string;
  /** Console Organization ID */
  console_org_id: unknown;
  /** 組織名 */
  name: string;
  /** 組織コード */
  code: string;
  /** 有効 */
  is_active: boolean;
  /** Creation timestamp */
  created_at?: DateTimeString;
  /** Last update timestamp */
  updated_at?: DateTimeString;
  /** Soft delete timestamp */
  deleted_at?: DateTimeString;
}

// ============================================================================
// I18n (Internationalization)
// ============================================================================

/**
 * Unified i18n object for OrganizationCache
 * Contains model label and all field labels/placeholders
 */
export const organizationCacheI18n = {
  /** Model display name */
  label: {"ja":"組織キャッシュ","en":"Organization Cache"},
  /** Field labels and placeholders */
  fields: {
    console_org_id: {
      label: {"ja":"Console Organization ID","en":"Console Organization ID"},
    },
    name: {
      label: {"ja":"組織名","en":"Organization Name"},
    },
    code: {
      label: {"ja":"組織コード","en":"Organization Code"},
    },
    is_active: {
      label: {"ja":"有効","en":"Active"},
    },
  },
} as const;

// ============================================================================
// Zod Schemas
// ============================================================================

/** Field schemas for OrganizationCache */
export const baseOrganizationCacheSchemas = {
  console_org_id: z.string(),
  name: z.string().min(1).max(100),
  code: z.string().min(1).max(20),
  is_active: z.boolean(),
} as const;

/** Create schema for OrganizationCache (POST requests) */
export const baseOrganizationCacheCreateSchema = z.object({
  console_org_id: baseOrganizationCacheSchemas.console_org_id,
  name: baseOrganizationCacheSchemas.name,
  code: baseOrganizationCacheSchemas.code,
  is_active: baseOrganizationCacheSchemas.is_active,
});

/** Update schema for OrganizationCache (PUT/PATCH requests) */
export const baseOrganizationCacheUpdateSchema = baseOrganizationCacheCreateSchema.partial();

// ============================================================================
// Inferred Types
// ============================================================================

export type BaseOrganizationCacheCreate = z.infer<typeof baseOrganizationCacheCreateSchema>;
export type BaseOrganizationCacheUpdate = z.infer<typeof baseOrganizationCacheUpdateSchema>;

// ============================================================================
// I18n Helper Functions
// ============================================================================

/** Get model label for a specific locale */
export function getOrganizationCacheLabel(locale: string): string {
  return organizationCacheI18n.label[locale as keyof typeof organizationCacheI18n.label] ?? organizationCacheI18n.label['en'] ?? 'OrganizationCache';
}

/** Get field label for a specific locale */
export function getOrganizationCacheFieldLabel(field: string, locale: string): string {
  const fieldI18n = organizationCacheI18n.fields[field as keyof typeof organizationCacheI18n.fields];
  if (!fieldI18n) return field;
  return fieldI18n.label[locale as keyof typeof fieldI18n.label] ?? fieldI18n.label['en'] ?? field;
}

/** Get field placeholder for a specific locale */
export function getOrganizationCacheFieldPlaceholder(field: string, locale: string): string {
  const fieldI18n = organizationCacheI18n.fields[field as keyof typeof organizationCacheI18n.fields];
  if (!fieldI18n || !('placeholder' in fieldI18n)) return '';
  const placeholder = fieldI18n.placeholder as Record<string, string>;
  return placeholder[locale] ?? placeholder['en'] ?? '';
}
