/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * Auto-generated TypeScript types from Omnify schemas.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: npx omnify generate
 */

import { z } from 'zod';
import type { DateTimeString } from './common';

/**
 * チームキャッシュ
 */
export interface TeamCache {
  /** Primary key */
  id: string;
  /** Console Team ID */
  console_team_id: unknown;
  /** Console Organization ID */
  console_org_id: unknown;
  /** チーム名 */
  name: string;
  /** Creation timestamp */
  created_at?: DateTimeString;
  /** Last update timestamp */
  updated_at?: DateTimeString;
  /** Soft delete timestamp */
  deleted_at?: DateTimeString;
}

// ============================================================================
// I18n (Internationalization)
// ============================================================================

/**
 * Unified i18n object for TeamCache
 * Contains model label and all field labels/placeholders
 */
export const teamCacheI18n = {
  /** Model display name */
  label: {"ja":"チームキャッシュ","en":"Team Cache"},
  /** Field labels and placeholders */
  fields: {
    console_team_id: {
      label: {"ja":"Console Team ID","en":"Console Team ID"},
    },
    console_org_id: {
      label: {"ja":"Console Organization ID","en":"Console Organization ID"},
    },
    name: {
      label: {"ja":"チーム名","en":"Team Name"},
    },
  },
} as const;

// ============================================================================
// Zod Schemas
// ============================================================================

/** Field schemas for TeamCache */
export const baseTeamCacheSchemas = {
  console_team_id: z.string(),
  console_org_id: z.string(),
  name: z.string().min(1).max(100),
} as const;

/** Create schema for TeamCache (POST requests) */
export const baseTeamCacheCreateSchema = z.object({
  console_team_id: baseTeamCacheSchemas.console_team_id,
  console_org_id: baseTeamCacheSchemas.console_org_id,
  name: baseTeamCacheSchemas.name,
});

/** Update schema for TeamCache (PUT/PATCH requests) */
export const baseTeamCacheUpdateSchema = baseTeamCacheCreateSchema.partial();

// ============================================================================
// Inferred Types
// ============================================================================

export type BaseTeamCacheCreate = z.infer<typeof baseTeamCacheCreateSchema>;
export type BaseTeamCacheUpdate = z.infer<typeof baseTeamCacheUpdateSchema>;

// ============================================================================
// I18n Helper Functions
// ============================================================================

/** Get model label for a specific locale */
export function getTeamCacheLabel(locale: string): string {
  return teamCacheI18n.label[locale as keyof typeof teamCacheI18n.label] ?? teamCacheI18n.label['en'] ?? 'TeamCache';
}

/** Get field label for a specific locale */
export function getTeamCacheFieldLabel(field: string, locale: string): string {
  const fieldI18n = teamCacheI18n.fields[field as keyof typeof teamCacheI18n.fields];
  if (!fieldI18n) return field;
  return fieldI18n.label[locale as keyof typeof fieldI18n.label] ?? fieldI18n.label['en'] ?? field;
}

/** Get field placeholder for a specific locale */
export function getTeamCacheFieldPlaceholder(field: string, locale: string): string {
  const fieldI18n = teamCacheI18n.fields[field as keyof typeof teamCacheI18n.fields];
  if (!fieldI18n || !('placeholder' in fieldI18n)) return '';
  const placeholder = fieldI18n.placeholder as Record<string, string>;
  return placeholder[locale] ?? placeholder['en'] ?? '';
}
