/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * Auto-generated TypeScript types from Omnify schemas.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: npx omnify generate
 */

import { z } from 'zod';
import type { DateTimeString } from './common';
import type { Role } from './Role';

/**
 * ユーザーキャッシュ
 */
export interface UserCache {
  /** Primary key */
  id: string;
  /** 名前 */
  name: string;
  /** メールアドレス */
  email: string;
  /** Console User ID */
  console_user_id?: unknown;
  /** 所属組織ID */
  console_org_id?: unknown;
  /** Console Access Token */
  console_access_token?: string;
  /** Console Refresh Token */
  console_refresh_token?: string;
  /** Console Token有効期限 */
  console_token_expires_at?: DateTimeString;
  /** ロール */
  roles: Role[];
  /** Creation timestamp */
  created_at?: DateTimeString;
  /** Last update timestamp */
  updated_at?: DateTimeString;
}

// ============================================================================
// I18n (Internationalization)
// ============================================================================

/**
 * Unified i18n object for UserCache
 * Contains model label and all field labels/placeholders
 */
export const userCacheI18n = {
  /** Model display name */
  label: {"ja":"ユーザーキャッシュ","en":"User Cache"},
  /** Field labels and placeholders */
  fields: {
    name: {
      label: {"ja":"名前","en":"Name"},
    },
    email: {
      label: {"ja":"メールアドレス","en":"Email"},
    },
    console_user_id: {
      label: {"ja":"Console User ID","en":"Console User ID"},
    },
    console_org_id: {
      label: {"ja":"所属組織ID","en":"Organization ID"},
    },
    console_access_token: {
      label: {"ja":"Console Access Token","en":"Console Access Token"},
    },
    console_refresh_token: {
      label: {"ja":"Console Refresh Token","en":"Console Refresh Token"},
    },
    console_token_expires_at: {
      label: {"ja":"Console Token有効期限","en":"Console Token Expiry"},
    },
    roles: {
      label: {"ja":"ロール","en":"Roles"},
    },
  },
} as const;

// ============================================================================
// Zod Schemas
// ============================================================================

/** Field schemas for UserCache */
export const baseUserCacheSchemas = {
  name: z.string().min(1),
  email: z.string().min(1),
  console_user_id: z.string().optional().nullable(),
  console_org_id: z.string().optional().nullable(),
  console_access_token: z.string().optional().nullable(),
  console_refresh_token: z.string().optional().nullable(),
  console_token_expires_at: z.string().datetime({ offset: true }).optional().nullable(),
} as const;

/** Create schema for UserCache (POST requests) */
export const baseUserCacheCreateSchema = z.object({
  name: baseUserCacheSchemas.name,
  email: baseUserCacheSchemas.email,
  console_user_id: baseUserCacheSchemas.console_user_id,
  console_org_id: baseUserCacheSchemas.console_org_id,
  console_access_token: baseUserCacheSchemas.console_access_token,
  console_refresh_token: baseUserCacheSchemas.console_refresh_token,
  console_token_expires_at: baseUserCacheSchemas.console_token_expires_at,
});

/** Update schema for UserCache (PUT/PATCH requests) */
export const baseUserCacheUpdateSchema = baseUserCacheCreateSchema.partial();

// ============================================================================
// Inferred Types
// ============================================================================

export type BaseUserCacheCreate = z.infer<typeof baseUserCacheCreateSchema>;
export type BaseUserCacheUpdate = z.infer<typeof baseUserCacheUpdateSchema>;

// ============================================================================
// I18n Helper Functions
// ============================================================================

/** Get model label for a specific locale */
export function getUserCacheLabel(locale: string): string {
  return userCacheI18n.label[locale as keyof typeof userCacheI18n.label] ?? userCacheI18n.label['en'] ?? 'UserCache';
}

/** Get field label for a specific locale */
export function getUserCacheFieldLabel(field: string, locale: string): string {
  const fieldI18n = userCacheI18n.fields[field as keyof typeof userCacheI18n.fields];
  if (!fieldI18n) return field;
  return fieldI18n.label[locale as keyof typeof fieldI18n.label] ?? fieldI18n.label['en'] ?? field;
}

/** Get field placeholder for a specific locale */
export function getUserCacheFieldPlaceholder(field: string, locale: string): string {
  const fieldI18n = userCacheI18n.fields[field as keyof typeof userCacheI18n.fields];
  if (!fieldI18n || !('placeholder' in fieldI18n)) return '';
  const placeholder = fieldI18n.placeholder as Record<string, string>;
  return placeholder[locale] ?? placeholder['en'] ?? '';
}
